<aside class="sitemap">
	        <a href="index.php">Home</a>
	        <a href="categories-main.php">Categories Main</a>
	        <a href="category-a.php">Category А</a>
	        <a href="category-b.php">Category B</a>     
	        <a href="tag.php">Tag</a>           
	        <a href="suppliers-main.php">Suppliers main page</a>  
	        <a href="suppliers-profile.php">Suppliers profile</a>   
	        <a href="news-main.php">News Main</a>   
	        <a href="expert-articles.php">Expert Articles Main</a>                
	        <a href="expert-article.php">Expert Article</a>   
	        <a href="all-products.php">All Products</a>       
	        <a href="all-reviews.php">All Reviews</a>                
	        <a href="product.php">Product Page</a>     
	        <a href="search-results.php">Search Page</a>    
	        <a href="subscribe-plan.php">Subscribe Plan</a>   
	        <a href="account.php">Account</a>   
	        <a href="account-settings.php">Account Settings</a>
	        <a href="create-product-and-services.php">Create Product &amp; Services</a>
	        <a href="create-expert-article.php">Create Expert Article</a> 
	        <a href="create-work-history.php">Create Work History</a>           
	        <a href="log-in.php">Log-in</a> 
	        <a href="create-personal-account-first.php">Create Personal Account 1</a>   
	        <a href="create-personal-account-second.php">Create Personal Account 2</a>   
	        <a href="create-company-account-first.php">Create Company Account 1</a>   
	        <a href="create-company-account-second.php">Create Company Account 2</a>  
	        <a href="congratulation.php">Congratulation</a>  
	        <a href="edit-all-products.php">Edit All Products</a>       
	        <a href="all-documents.php">All Documents</a> 
	        <a href="edit-documents.php">Edit Documents</a> 
	        <a href="edit-suppliers-profile.php">Edit Suppliers profile</a>        
	        <a href="edit-product.php">Edit Product</a>          
	        <a href="edit-work-history.php">Edit Work History</a>        
	        <a href="edit-expert-article.php">Edit Expert Article</a>  
		</aside>